location_name = "eastus2"
resource_group_name = "rg-shorturl2"
storage_account_name = "stazfuncshorturl2"
plan_name = "plan-azfuncshorturl2"
app_insights_name = "appis-azfuncshorturl2"
func_name = "azfunc-shorturl2"
keyvault_name = "kv-shorturl2"
cosmos_name = "cosmos-shorturl2"
cosmosPrimaryKeyEmulator = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
cosmosConfigTemplateEmulator = "ewoJInVzZUNvc21vcyI6IHRydWUsCgkidXJpIjogImh0dHBzOi8vbG9jYWxob3N0OjgwODEiLAoJInByaW1hcnlLZXkiOiAie3twcmltYXJ5S2V5fX0iLAoJInByaW1hcnlDb25uZWN0aW9uU3RyaW5nIjogIkFjY291bnRFbmRwb2ludD1odHRwczovL2xvY2FsaG9zdDo4MDgxLztBY2NvdW50S2V5PXt7cHJpbWFyeUtleX19IiwKCSJpZGVudGl0eVNlcnZlck9wZXJhdGlvbmFsU3RvcmUiOiB7CgkJImRhdGFiYXNlIjogImRiLXNob3J0VXJsIiwKCQkiY29sbGVjdGlvbiI6ICJvcGVyYXRpb25hbCIKCX0KfQ=="
cosmosConfigTemplateProduction = "ewoJInVzZUNvc21vcyI6IHRydWUsCgkidXJpIjogImh0dHBzOi8vY29zbW9zLXNob3J0dXJsMi5kb2N1bWVudHMuYXp1cmUuY29tOjQ0MyIsCgkicHJpbWFyeUtleSI6ICJ7e3ByaW1hcnlLZXl9fSIsCgkicHJpbWFyeUNvbm5lY3Rpb25TdHJpbmciOiAiQWNjb3VudEVuZHBvaW50PWh0dHBzOi8vY29zbW9zLXNob3J0dXJsMi5kb2N1bWVudHMuYXp1cmUuY29tOjQ0My87QWNjb3VudEtleT17e3ByaW1hcnlLZXl9fSIsCgkiaWRlbnRpdHlTZXJ2ZXJPcGVyYXRpb25hbFN0b3JlIjogewoJCSJkYXRhYmFzZSI6ICJkYi1zaG9ydFVybCIsCgkJImNvbGxlY3Rpb24iOiAib3BlcmF0aW9uYWwiCgl9Cn0="

# export ARM_ACCESS_KEY=$(az keyvault secret show --name terraform-backend-key --vault-name kv-tf-shorturl2 --query value -o tsv)

